config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "help" => "home#help"
  get "contact" => "home#contact"

  resources :users, only: :show
  resources :hotels, only: %i[index show] do
    resources :reservations, except: :index
  end
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms
  has_many :reservations

  validates :name, uniqueness: { scope: :city }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
  belongs_to :room

  before_create :set_status

  before_save :calculate_price

  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :rooms, presence: true
  validate :checked_in_dates

  scope :active, -> { where("status = 'booked' and check_out >= #{Date.today}") }

  def destroy!
    update(status: 'cancel')
  end

  private

  def set_status
    return if status

    self.status = 'booked'
  end

  def calculate_price
    self.price = room.price * rooms * (check_out - check_in).to_i
  end

  def checked_in_dates
    errors.add(:check_in, "can't be a past date") if check_in&.before?(Date.today)
    errors.add(:check_in, "can't be after checkout") if check_out.present? && check_in&.after?(check_out)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations

  validates :email, uniqueness: true

  def upcoming_reservations
    reservations.where("check_in >= ? and status = 'booked'", Date.today).order(:check_in)
  end

  def ongoing_reservations
    reservations.where("check_in < ? and check_out >= ? and status = 'booked'", Date.today,
                       Date.today).order(:check_in)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def contact; end

  def help; end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: :show

  def index
    @hotels = Hotel.includes(:rooms).where('city = ?', params[:search])
    respond_to do |format|
      format.js {}
    end
  end

  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_hotel
    @hotel = Hotel.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def hotel_params
    params.fetch(:hotel, {})
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[show edit update destroy]
  before_action :set_hotel

  def show; end

  def new
    @reservation = @hotel.reservations.build(room_id: params[:room_id])
  end

  def edit; end

  def create
    @reservation = @hotel.reservations.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to root_path, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to root_path, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reservation.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Reservation was successfully cancelled.' }
      format.json { head :no_content }
    end
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def set_hotel
    @hotel = Hotel.find_by(id: params[:hotel_id]) || @reservation&.hotel
  end

  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out, :name, :email, :guests, :rooms, :room_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h2>Welcome to Altimetrik Hotels</h2>

<%= form_tag hotels_path, method: :get, remote: true do %>
  <%= label_tag :query, "Search for:" %>
  <%= text_field_tag :search %>
  <%= submit_tag "Search" %>
<% end %>

<div id='hotels_list'></div>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
	<h2><%= hotel.name %></h2>
	<p>Phone: <%= hotel.contact %></p>
	<p>Email: <%= hotel.email %></p>
	<p>City: <%= hotel.city %></p>
	<% hotel.rooms.each do |room| %>
	  Room Type: <%= room.room_type %>
	  Max Guests: <%= room.max_guests %>
	  Price: Rs <%= room.price %>
	  <%= link_to 'Book', new_hotel_reservation_path(hotel, room_id: room.id) %><br/>
	<% end %>  
</div>

app/views/hotels/_hotels.html.erb
<ul>
	<% hotels.each do |hotel| %>
  	<li><%= render "hotel", hotel: hotel %></li>
	<% end %>
</ul>	

app/views/hotels/index.js.erb
$('#hotels_list').html("<%= j render "hotels", hotels: @hotels %>")

app/views/hotels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hotel %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Altimetrik Hotels", '/', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "My Bookings", user_path(id: 1) %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AltHotels</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
     <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: [hotel, reservation]) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :room_id, value: reservation.room_id %>
  <!-- As there is no authentication as of now, by default we are making the 1st user's reservation  -->
  <%= form.hidden_field :user_id, value: User.first&.id %>
  Check In: <%= form.date_field :check_in, min: Date.today %>
  Check Out: <%= form.date_field :check_out, min: Date.tomorrow %><br/>
  Name: <%= form.text_field :name %><br/>
  Email: <%= form.email_field :email %><br/>
  No. of Guests: <%= form.text_field :guests %><br/>
  Rooms: <%= form.text_field :rooms %><br/>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation, hotel: @hotel %>

<br>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render "form", reservation: @reservation, hotel: @hotel %>

<br>

<div>
  <%= link_to "Back to reservations", hotel_reservations_path %>
</div>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>
  <%= link_to "Edit this reservation", edit_hotel_reservation_path(@reservation.hotel, @reservation) %> |

  <%= button_to "Destroy this reservation", [@reservation.hotel, @reservation], method: :delete %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
	<% if user.upcoming_reservations.present? %>
	  <ul>
			Reservations: <% user.reservations.active.each do |reservation| %>
			  <li>Hotel: <%= reservation.hotel.name %><br/>
			  Check In: <%= reservation.check_in %><br/>
			  Check Out: <%= reservation.check_out %><br/>
			  No. of Guests: <%= reservation.guests %><br/>
			  No. of Rooms: <%= reservation.rooms %><br/>
			  Room Type: <%= reservation.room.room_type %><br/>
			  Price: Rs <%= reservation.price %><br/>
			  <%= link_to 'Modify', edit_hotel_reservation_path(reservation.hotel, reservation) %>
			  <%= link_to 'Cancel', [reservation.hotel, reservation], method: :delete, data: { confirm: 'Are you sure?' } %></li>
			<% end %>
		</ul>
	<% else %>
	  <h3>No Upcoming Bookings</h3>	
	<% end %>	
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>